#pragma once

typedef enum es_status {
    ES_EOK,

    ES_ENOMEM,
    ES_ESTATE,
    ES_ENOTSUPP,
    ES_EIO,
    ES_EINVAL,

    /* params */
    ES_EPARAMMISSING,
    ES_EPARAMINVALID,
    ES_EPARAMINSUFFICIENT,

    /* connection */
    ES_ECONNFAIL,
    ES_EDNSFAIL,
    ES_ESENDFAIL,
    ES_ESKCREATEFAIL,
    ES_ESKBINDFAIL,
    ES_ESKCLOEXECFAIL,
    ES_ESKNONBLOCKFAIL,

    ES_ENODATA,
    ES_ERECVFAIL,
    ES_ERESPONSEINVALID,

    ES_EWRONGTID,

    ES_ESCRIPTFAIL,
} es_status;
